openapi: 3.0.3
info:
  title: 'Fraud0 API Backend'
  description: 'This api documentation is for the hiring process of Fraud0'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/placements:
    get:
      summary: 'Display a listing of placements.'
      operationId: displayAListingOfPlacements
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The platform must be either web or app.'
                  errors:
                    platform:
                      - 'The platform must be either web or app.'
                properties:
                  message:
                    type: string
                    example: 'The platform must be either web or app.'
                  errors:
                    type: object
                    properties:
                      platform:
                        type: array
                        example:
                          - 'The platform must be either web or app.'
                        items:
                          type: string
      tags:
        - 'Placement endpoints'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                sort_by:
                  type: string
                  description: 'Field to sort by. Possible values: key, platform, total, invalid_total, invalid_total_percent, pixel_stuffing, pixel_stuffing_percent, viewable, viewable_percent, non_viewable, non_viewable_percent, mfa_site_symptoms, mfa_site_symptoms_percent, other_invalid, other_invalid_percent.'
                  example: total
                sort_order:
                  type: string
                  description: 'Sort order. Possible values: asc, desc.'
                  example: desc
                per_page:
                  type: integer
                  description: 'Number of results per page.'
                  example: 10
                page:
                  type: integer
                  description: 'Page number.'
                  example: 1
                paginate:
                  type: boolean
                  description: 'Whether to paginate results. Default value: true.'
                  example: true
                key:
                  type: string
                  description: 'Optional. Filter by key (case-insensitive).'
                  example: '""'
                platform:
                  type: string
                  description: 'Optional. Filter by platform. Possible values: ["","app", "web"].'
                  example: '""'
                min_total:
                  type: integer
                  description: 'Optional. Filter placements with total greater than or equal to this value.'
                  example: 0
                min_invalid_total:
                  type: integer
                  description: 'Optional. Filter placements with invalid_total greater than or equal to this value.'
                  example: 0
      security: []
tags:
  -
    name: 'Placement endpoints'
    description: ''
